### PR TITLE
Add ChatBees vs OpenAI RAG benchmark to tonic validate examples

### PR DESCRIPTION
**Pull request by ndb-rkang**
Compares ChatBees (www.chatbees.ai) vs openAI RAG quality

### CODE REVIEW

**Comment by joeferraratonic** [comment]
Hi @ndb-rkang, thank you for the PR! We love seeing new RAG comparisons.

I ran your notebook to verify your results and I got a different enough average to flag it here. The mean answer similarity score I got when running your notebook was 4.11 with a standard deviation of 1.40. This is compared to a mean of 4.58 and standard deviation of 0.79 in the notebook in your PR. I manually reviewed the questions and answers where the scores differed and saw that the answers I got could be significantly different than the answers you got. I attached the `cb_run.csv` file I got when running the notebook below. Do you know what could be causing the discrepancy?

[cb_run.csv](https://github.com/TonicAI/tonic_validate/files/14763652/cb_run.csv)

We're happy to add your comparison to the repo, we just want to make sure that the results are reproducible. Your RAG project looks interesting. I was very happy I could run the notebook without having to sign up for an account or ask you for an API key!

**Comment by ndb-rkang** [comment]
@joeferraratonic thanks for the quick turnaround! I suspect the difference is caused by an optimization that's yet to be released (i was running the benchmark against a local server). I ran it again with the optimization disabled, and was able to get ~4.1 average score :) I'll ping this thread again when the optimization is released, sorry for the churn! 

Another question about the eval dataset. Do you have any recommendation on a larger dataset we can try our RAG on?

**Comment by joeferraratonic** [comment]
@ndb-rkang Great, I'm looking forward to when the new optimization is released!

Per your question about datasets, LlamaIndex has some datasets that are good for evaluation that you can find here: [https://llamahub.ai/?tab=llama_datasets](https://llamahub.ai/?tab=llama_datasets). Some of them are larger than others.

**Comment by ndb-rkang** [comment]
@joeferraratonic confirmed that i am able to repro the original 4.6 result with updated server. There're some run-to-run variance of <0.1, but overall i was able to get similar results. Let me know if you can also repro!

Re llama dataset - thanks for the tip! Will take a look and see if our solution generalizes well :)

**Comment by joeferraratonic** [comment]
@ndb-rkang looks good I was able to repro. I'll approve and merge.

Out of curiosity, what can you say about the RAG architecture you use for your app? Your documentation doesn't say much about it. I'm curious even what LLM your using?

**Review by joeferraratonic — APPROVED** [review]
Looks good, I was able to repro results.

**Pull request merged**
